import { writeFileSync } from 'node:fs';
import { FIELDS } from '../packages/soonish/src/engine/fields';
import { CHANNELS, compileField, emitCSS } from '../packages/soonish/src/engine/compile';

const compiled = FIELDS.map((f) => compileField(f.name, f.slug, f.field, { duration: f.duration }));

// ---- verification ----
let fail = 0;
for (const c of compiled) {
  const all = CHANNELS.flatMap((ch) => c.curves[ch]).flat();
  const outOfRange = all.filter((v) => v < 0 || v > 1).length;
  const unclosed = CHANNELS.flatMap((ch) => c.curves[ch]).filter((cv) => cv[0] !== cv[cv.length - 1]).length;
  const badRefs = c.dots.filter(
    (d) => d.d >= c.combos.length || d.g >= c.curves.g.length,
  ).length;
  // Dots whose curve never moves are dropped by design — they render at the
  // stylesheet's resting opacity. Reported, not failed: a high count usually
  // means the field simply doesn't reach those cells.
  const staticDots = c.dots.filter((d) => {
    const cb = c.combos[d.d];
    return cb.o < 0 && cb.s < 0 && d.g < 0;
  }).length;
  const per = CHANNELS.map((ch) => `${ch}=${c.curves[ch].length}`).join(' ');
  const total = CHANNELS.reduce((n, ch) => n + c.curves[ch].length, 0);
  if (outOfRange || unclosed || badRefs) fail++;
  console.log(
    `${c.name.padEnd(13)} ${per.padEnd(14)} total=${String(total).padStart(2)}  ` +
      `range=${Math.min(...all).toFixed(2)}-${Math.max(...all).toFixed(2)}  ` +
      `rules=${c.combos.length}+${c.curves.g.length}g  ` +
      `outOfRange=${outOfRange} unclosed=${unclosed} badRefs=${badRefs} static=${staticDots}`,
  );
}

const css = compiled.map(emitCSS).join('\n\n');
writeFileSync(
  'packages/soonish/src/styles/fields.generated.css',
  `/* GENERATED by scripts/compile-fields.ts — do not edit by hand. */\n` + css.trim() + '\n',
);
const out = `// GENERATED by scripts/compile-fields.ts — do not edit by hand.
// Only the sampled curve data lives here; the CSS goes to
// styles/fields.generated.css and nothing in engine/ reaches the browser.
import type { CompiledDot } from './compile';

export const FIELD_DOTS: Record<string, { name: string; duration: number; dots: CompiledDot[] }> = {
${compiled
  .map(
    (c) =>
      `  '${c.slug}': { name: ${JSON.stringify(c.name)}, duration: ${c.duration}, dots: ${JSON.stringify(c.dots)} },`,
  )
  .join('\n')}
};
`;
writeFileSync('packages/soonish/src/engine/generated.ts', out);
console.log(`\nCSS bytes: ${css.length}  |  failures: ${fail}`);
